services:
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev
    restart: always
    container_name: api_travel_offer
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - N8N_INTERNAL_URL=http://n8n:5678
      - N8N_EXTERNAL_URL=https://n8n.element.travel
    env_file:
      - .env
    volumes:
      - ../logs:/app/logs
      - ../src:/app/src
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - d_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  d_net:
    external: true